- name: Create directories
  file:
    path: "{{ docker_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_user_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ docker_path }}"
    - "{{ app_path }}"
    - "{{ app_path }}/checker-files"
  tags:
    - dir

- name: Update git repository
  become_user: "{{ app_user }}"
  git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_path }}/src"
    accept_hostkey: yes
    force: yes
    clone: yes

- name: Copy dotenv template
  template:
    src: "templates/.env.j2"
    dest: "{{ app_path }}/.env"
    owner: "{{ app_user }}"
    group: "{{ app_user_group }}"
    mode: "0644"

- name: Copy docker compose template
  template:
    src: "templates/docker-compose.yml.j2"
    dest: "{{ app_path }}/docker-compose.yml"
    owner: "{{ app_user }}"
    group: "{{ app_user_group }}"
    mode: "0644"

- name: Launch docker build
  become_user: "{{ app_user }}"
  shell:
    cmd: docker-compose build
    chdir: "{{ app_path }}"

- name: Apply db migrations
  become_user: "{{ app_user }}"
  shell:
    cmd: docker-compose run --rm bot rake db:migrate
    chdir: "{{ app_path }}"

- name: Launch docker compose
  become_user: "{{ app_user }}"
  shell:
    cmd: docker-compose up -d hub node-firefox db bot
    chdir: "{{ app_path }}"

# - name: Launch bot
#   become_user: "{{ app_user }}"
#   shell:
#     cmd: docker-compose up -d --force-recreate --no-deps bot
#     chdir: "{{ app_path }}"

- name: Update vnc password
  become_user: "{{ app_user }}"
  shell:
    cmd: docker-compose exec node-firefox /bin/bash -c "x11vnc -storepasswd {{ vnc_password }} /home/seluser/.vnc/passwd"
    chdir: "{{ app_path }}"

# - name: Add run check to crontab
#   become_user: "{{ app_user }}"
#   cron:
#     name: "Run queue checker"
#     minute: "*/5"
#     job: "cd {{ app_path }}; docker-compose up -d --force-recreate hub; sleep 5; docker-compose up checker >> checker.log 2>&1"

- name: Add send stat to crontab
  become_user: "{{ app_user }}"
  cron:
    name: "Send stat"
    hour: "6"
    job: "cd {{ app_path }}; docker-compose run --rm bot bin/send_stat >> send_stat.log 2>&1"

# - name: Restart firefox
#   become_user: "{{ app_user }}"
#   shell:
#     cmd: docker-compose restart node-firefox
#     chdir: "{{ app_path }}"
