# SSH Settings
#
---
- name: Prevent root login
  replace: "dest=/etc/ssh/sshd_config regexp='^#PermitRootLogin yes$' replace='PermitRootLogin no'"

- name: Disable password authentication
  replace: "dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication yes$' replace='PasswordAuthentication no'"

- name: Reload sshd
  service: name=ssh state=reloaded
