# Accounts, keys.
---

- name: Add users
  user:
    name: "{{ item.name }}"
    groups: ['sudo', 'docker']
    shell: /bin/bash
  with_items: "{{ ssh_users }}"

- name: Remove old users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ users_to_remove }}"
  tags: remove_old_users

- name: Add ssh users keys
  authorized_key: user={{ item.name }} state=present key="{{ item.key }}"
  with_items: "{{ ssh_users }}"

- name: Create app user
  user:
    name: "{{ app_user }}"
    groups: ['sudo', 'docker']
    shell: /bin/bash
    generate_ssh_key: True
  when: app_user is defined

- name: Add ssh keys to user "{{ app_user }}"
  authorized_key: user={{ app_user }} state=present key="{{ item.key }}"
  with_items: "{{ ssh_users }}"

- name: Allow sudo users to perform sudo commands without password
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD: ALL'"
