en:
  greeting_message: |
    Hi! Kdmid bot checks queue on sites like *.kdmid.ru for <b>free slots</b>.

    For beginning please send me a link that your receive after registration on the site.
    Link should looks like: https://istanbul.kdmid.ru/queue/OrderInfo.aspx?id=123&cd=123

  task_added_message: |
    Your link was successfully added!
    I'll notify you when free slots become available.

  url_invalid_message: |
    Sorry, but your link is invalid or unavailable now!
    Please check it opens in the browser correctly.

  dont_understand_message: I don't understand you :(
  farewell_message: Bye! I'll miss you :(

  activemodel:
    errors:
      record_invalid: "record invalid: %{errors}"
  errors:
    format: '%{attribute}%{message}'
    url:
      invalid: "url is invalid"
      not_available: "url is not available"
